profile_service_url = "http://profile_service:8000/api/v1"
rating_service_url = "http://rating_service:8001/api/v1"

[db]
host = "matching_service_db"
port = 5432
user = "postgres"
password = "postgres"
name = "postgres"

[rmq]
host = "rabbitmq"
port = 5672
user = "guest"
password = "guest"