profile_service_url = "http://profile_service:8000/api/v1"

[db]
host = "db"
port = 5432
user = "postgres"
password = "postgres"
name = "postgres"

[rmq]
host = "rabbitmq"
port = 5672
user = "guest"
password = "guest"