profile_service_url = "http://localhost:8000/api/v1"

[db]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
name = "postgres"

[rmq]
host = "localhost"
port = 5672
user = "guest"
password = "guest"