# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/protos/matching.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'components/protos/matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n components/protos/matching.proto\x12\x08matching\"%\n\x12\x46indMatchesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x13\x46indMatchesResponse\x12\x18\n\x10matched_user_ids\x18\x01 \x03(\t2V\n\x08Matching\x12J\n\x0b\x46indMatches\x12\x1c.matching.FindMatchesRequest\x1a\x1d.matching.FindMatchesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'components.protos.matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_FINDMATCHESREQUEST']._serialized_start = 46
    _globals['_FINDMATCHESREQUEST']._serialized_end = 83
    _globals['_FINDMATCHESRESPONSE']._serialized_start = 85
    _globals['_FINDMATCHESRESPONSE']._serialized_end = 132
    _globals['_MATCHING']._serialized_start = 134
    _globals['_MATCHING']._serialized_end = 220
# @@protoc_insertion_point(module_scope)
