profile_service_url = "http://localhost:8000/api/v1/profiles"
rating_service_url = "http://localhost:8001/api/v1/ratings"
matching_service_url = "http://localhost:8002/api/v1"

[bot]
bot_token = "7595911850:AAHs-6bjlqCrO_eqLC_eVu1L4HEW-2nv4M0"

[redis]
host = "localhost"
port = 6379
