profile_service_url = "http://profile_service:8000/api/v1"
rating_service_url = "http://rating_service:8001/api/v1"
matching_service_url = "http://matching_service:8002/api/v1"

[bot]
bot_token = "7530248180:AAERIBY0gJZebSGfRg1sbI8m1IJNz_PT84s"

[redis]
host = "redis"
port = 6379
