profile_service_url = "http://localhost:8000/api/v1"
rating_service_url = "http://localhost:8001/api/v1"
matching_service_url = "http://localhost:8002/api/v1"

[bot]
bot_token = "7066916393:AAFOAZtmf__xt9Fl-XSM9GpTQvddn98skkI"

[redis]
host = "localhost"
port = 6379
