profile_service_url = "http://profile_service:8000/api/v1"
rating_service_url = "http://rating_service:8001/api/v1"
matching_service_url = "http://matching_service:8002/api/v1"

[bot]
bot_token = "7066916393:AAFOAZtmf__xt9Fl-XSM9GpTQvddn98skkI"

[redis]
host = "redis"
port = 6379
