profile_service_url = "http://localhost:8000/api/v1"

[bot]
bot_token = "7530248180:AAFTCvZdxlPd-7Z5Se8qFVSRbOCTNAtqonc"

[rmq]
host = "localhost"
port = 5672
user = "guest"
password = "guest"

[celery]
broker_url = 'redis://localhost:6379/0'
