profile_service_url = "http://profile_service/api/v1"
matching_service_url = "http://matching_service/api/v1"

[bot]
bot_token = "7530248180:AAFTCvZdxlPd-7Z5Se8qFVSRbOCTNAtqonc"

[rmq]
host = "rabbitmq"
port = 5672
user = "guest"
password = "guest"

[celery]
broker_url = 'redis://redis:6379/0'
