profile_service_url = "http://profile_service/api/v1"

[bot]
bot_token = "7595911850:AAHs-6bjlqCrO_eqLC_eVu1L4HEW-2nv4M0"

[rmq]
host = "rabbitmq"
port = 5672
user = "guest"
password = "guest"

[celery]
broker_url = 'redis://redis:6379/0'
