profile_service_url = "http://profile_service:8000/api/v1"
matching_service_url = "http://matching_service:8002/api/v1"

[db]
host = "rating_service_db"
port = 5432
user = "postgres"
password = "postgres"
name = "postgres"